import {
  type WorkoutDetail,
  WorkoutDetailSchema,
} from "@/schemas/workout-session.schema";

export const DEFAULT_WORKOUT_ROUTINES: Record<string, WorkoutDetail> = {
  rtn_fbw_01: {
    id: "rtn_fbw_01",
    title: "FBW dla Początkujących",
    description: "Kompleksowy trening całego ciała z wolnymi ciężarami.",
    durationMinutes: 45,
    level: "beginner",
    targetMuscleGroups: ["Klatka", "Plecy", "Nogi", "Barki"],
    exercises: [
      {
        id: "ex_fbw_1",
        name: "Przysiad ze sztangą na plecach",
        targetMuscle: "Nogi",
        sets: 3,
        targetReps: "10-12",
        restSeconds: 90,
        completed: false,
      },
      {
        id: "ex_fbw_2",
        name: "Wyciskanie sztangi leżąc",
        targetMuscle: "Klatka piersiowa",
        sets: 3,
        targetReps: "8-10",
        restSeconds: 90,
        completed: false,
      },
      {
        id: "ex_fbw_3",
        name: "Wiosłowanie hantlem w opadzie",
        targetMuscle: "Plecy",
        sets: 3,
        targetReps: "10-12",
        restSeconds: 60,
        completed: false,
      },
      {
        id: "ex_fbw_4",
        name: "Wyciskanie żołnierskie (OHP)",
        targetMuscle: "Barki",
        sets: 3,
        targetReps: "10-12",
        restSeconds: 60,
        completed: false,
      },
      {
        id: "ex_fbw_5",
        name: "Plank (Deska)",
        targetMuscle: "Brzuch",
        sets: 3,
        targetReps: "45-60 sek",
        restSeconds: 45,
        completed: false,
      },
    ],
  },
  rtn_push_02: {
    id: "rtn_push_02",
    title: "Push (Klatka + Barki + Triceps)",
    description: "Skupienie na mięśniach pchających i budowie siły.",
    durationMinutes: 55,
    level: "intermediate",
    targetMuscleGroups: ["Klatka", "Barki", "Triceps"],
    exercises: [
      {
        id: "ex_push_1",
        name: "Wyciskanie sztangi na ławce poziomej",
        targetMuscle: "Klatka piersiowa",
        sets: 4,
        targetReps: "6-8",
        restSeconds: 120,
        completed: false,
      },
      {
        id: "ex_push_2",
        name: "Wyciskanie hantli na skosie dodatnim",
        targetMuscle: "Górna klatka",
        sets: 3,
        targetReps: "10-12",
        restSeconds: 90,
        completed: false,
      },
      {
        id: "ex_push_3",
        name: "Wznosy bokiem z hantlami",
        targetMuscle: "Barki",
        sets: 4,
        targetReps: "12-15",
        restSeconds: 60,
        completed: false,
      },
      {
        id: "ex_push_4",
        name: "Dipsy na poręczach",
        targetMuscle: "Klatka i Triceps",
        sets: 3,
        targetReps: "8-10",
        restSeconds: 90,
        completed: false,
      },
      {
        id: "ex_push_5",
        name: "Prostowanie ramion na wyciągu",
        targetMuscle: "Triceps",
        sets: 3,
        targetReps: "12-15",
        restSeconds: 60,
        completed: false,
      },
    ],
  },
  rtn_pull_03: {
    id: "rtn_pull_03",
    title: "Pull (Plecy + Tył barku + Biceps)",
    description: "Rozwój szerokości i grubości pleców oraz ramion.",
    durationMinutes: 50,
    level: "intermediate",
    targetMuscleGroups: ["Plecy", "Biceps"],
    exercises: [
      {
        id: "ex_pull_1",
        name: "Podciąganie na drążku nachwytem",
        targetMuscle: "Najszerszy grzbietu",
        sets: 4,
        targetReps: "6-8",
        restSeconds: 120,
        completed: false,
      },
      {
        id: "ex_pull_2",
        name: "Wiosłowanie sztangą w opadzie tułowia",
        targetMuscle: "Plecy",
        sets: 4,
        targetReps: "8-10",
        restSeconds: 90,
        completed: false,
      },
      {
        id: "ex_pull_3",
        name: "Face Pulls z liną na wyciągu",
        targetMuscle: "Tył barku",
        sets: 3,
        targetReps: "12-15",
        restSeconds: 60,
        completed: false,
      },
      {
        id: "ex_pull_4",
        name: "Uginanie przedramion z hantlami z supinacją",
        targetMuscle: "Biceps",
        sets: 3,
        targetReps: "10-12",
        restSeconds: 60,
        completed: false,
      },
    ],
  },
  rtn_legs_04: {
    id: "rtn_legs_04",
    title: "Legs & Core (Nogi + Brzuch)",
    description: "Potężny bodziec na dolne partie ciała i stabilizację tułowia.",
    durationMinutes: 60,
    level: "advanced",
    targetMuscleGroups: ["Nogi", "Brzuch"],
    exercises: [
      {
        id: "ex_legs_1",
        name: "Przysiady ze sztangą na plecach",
        targetMuscle: "Czworogłowe i pośladki",
        sets: 4,
        targetReps: "6-8",
        restSeconds: 120,
        completed: false,
      },
      {
        id: "ex_legs_2",
        name: "Rumuński martwy ciąg (RDL)",
        targetMuscle: "Dwugłowe i pośladki",
        sets: 4,
        targetReps: "8-10",
        restSeconds: 90,
        completed: false,
      },
      {
        id: "ex_legs_3",
        name: "Wypychanie ciężaru na suwnicy",
        targetMuscle: "Nogi",
        sets: 3,
        targetReps: "10-12",
        restSeconds: 90,
        completed: false,
      },
      {
        id: "ex_legs_4",
        name: "Wspięcia na palce stojąc",
        targetMuscle: "Łydki",
        sets: 4,
        targetReps: "15-20",
        restSeconds: 45,
        completed: false,
      },
      {
        id: "ex_legs_5",
        name: "Unoszenie nóg w zwisie na drążku",
        targetMuscle: "Brzuch",
        sets: 3,
        targetReps: "12-15",
        restSeconds: 60,
        completed: false,
      },
    ],
  },
};

export function getWorkoutDetail(id: string): WorkoutDetail | null {
  const routine = DEFAULT_WORKOUT_ROUTINES[id];
  if (!routine) return null;
  const parsed = WorkoutDetailSchema.safeParse(routine);
  return parsed.success ? parsed.data : null;
}
